version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.11.1
        steps:
            - checkout
            - run: echo "npm installing"
            - run: npm install
    test:
        docker:
            - image: circleci/node:8.11.1
        steps:
            - checkout
            - run: echo "npm testing"
            - run: npm install
            - run: npm run test
workflows:
    version: 2
    build-test:
        jobs:
            - build
            - test
